# Generated by Django 2.0 on 2018-02-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squad_pantry_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdishrelation',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad_pantry_app.Dish'),
        ),
    ]
