# Generated by Django 2.0 on 2018-02-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad_pantry_app', '0002_auto_20180206_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('average_throughput', models.IntegerField(editable=False)),
                ('average_turnaround_time', models.DurationField(editable=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='created_at_idx'),
        ),
    ]
