# Generated by Django 2.0 on 2018-02-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squad_pantry_app', '0002_auto_20180202_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
