# Generated by Django 2.0 on 2018-02-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad_pantry_app', '0002_auto_20180206_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True, unique=True)),
                ('average_throughput', models.DecimalField(decimal_places=5, max_digits=10)),
                ('average_turnaround_time', models.TimeField()),
            ],
        ),
    ]
