# Generated by Django 2.0 on 2018-02-03 05:35

from django.db import migrations, models
import django.db.models.deletion
import squad_pantry_app.custom_valdidators


class Migration(migrations.Migration):

    dependencies = [
        ('squad_pantry_app', '0003_remove_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdishrelation',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad_pantry_app.Dish', validators=[squad_pantry_app.custom_valdidators.validate_dishes]),
        ),
    ]
