# Generated by Django 2.0 on 2018-02-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad_pantry_app', '0004_auto_20180208_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemetrics',
            name='average_turnaround_time',
            field=models.DurationField(editable=False),
        ),
    ]
