# Generated by Django 2.0 on 2018-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad_pantry_app', '0004_auto_20180207_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemetrics',
            name='average_throughput',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='day',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
