# Generated by Django 2.0 on 2018-02-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squad_pantry_app', '0005_auto_20180207_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='day',
            new_name='created_at',
        ),
    ]
